QEDjl-project/QEDbase.jl

.gitlab-ci.yml

see [documentation](https://github.com/QEDjl-project/QED.jl/blob/dev/docs/src/ci.md#unit-tests-for-ci-users)

ci: add unit tests

---

.gitlab-ci.yml

Integration tests checks if all QED sub packages are still working with the code changes in a PR, if they use the sub package, where the PR is open.
This [test PR](https://github.com/QEDjl-project/QEDbase.jl/pull/3) demonstrate, how it works.
- This [commit](https://github.com/QEDjl-project/QEDbase.jl/pull/3/commits/e9c2f31ef827d05a0d67c40cde066e708e05d88a) introduces an API break. Therefore the [integration test job](https://gitlab.com/hzdr/qedjl-project/QEDbase-jl/-/jobs/4964972487) fails.
- The following up [commit](https://github.com/QEDjl-project/QEDbase.jl/pull/3/commits/fd3d7816ae00d0548eeb52cbcfe21d35d25e86d2) points to a feature branch in the commit message, which solves the API break for the using sub package. Therefore the [test …

add integration tests

---

.formatting/format_all.jl
.gitlab-ci.yml

Before the format_all.jl script needs to be execute from the project root directory. Now the script can be executed from every directory path.

make format_all.jl path independent

---

.gitlab-ci.yml

- tests also the latest unreleased version 1.10 (can fail)
- integration tests still testing a single version. Will be extended in another PR.

run unit tests for Julia 1.6 until 1.9

---

.github/workflows/CompatHelper.yml

Add Compat Helper CI job 
Generated a ssh key pair for the deployment and add it to the repository like described in the [compat helper documentation](https://juliaregistries.github.io/CompatHelper.jl/stable/#Creating-SSH-Key).
The job cannot be triggered, until it was merged in dev. We had already the problem in #28 . 
This PR is a copy of: https://github.com/QEDjl-project/QEDprocesses.jl/pull/27

add CompatHelper CI Job

---

src/particles/particle_states.jl
test/particles.jl

Base state fix

---

Project.toml
src/particles/particle_states.jl
test/dirac_tensor.jl
test/four_momentum.jl
test/gamma_matrices.jl
test/lorentz_interface.jl
test/lorentz_vector.jl
test/particle_spinors.jl
test/particles.jl
test/runtests.jl
test/utils.jl

This PR improves the coverage for coordinates tested in `test/particle.jl` to the full domains for angles in spherical coordinates for photons. 
- added safetestsets to modulize the unit tests
- added more cases for the angles in spherical coordinates
- added a fix for #49 
This resolves #49

Improve parameter coverage in particle unit test

---

src/QEDbase.jl

They were missing from the exports so I added them.

Add is_incoming and is_outgoing to exports

---

src/interfaces/particle_interface.jl
src/particles/particle_direction.jl
src/particles/particle_spin_pol.jl
test/particles.jl

We add scalar broadcasting for `AbstractParticle`, `ParticleDirection`, and `AbstractSpinOrPolarization`. For instance, if one has a function `func(spin::SpinUp,x::Real)` and wants to perform a broadcast over `x`, one can now do 
```julia
x_vec = rand(10)
func.(SpinUp(),x_vec)
```
instead of `func.(Ref(SpinUp()),x_vec)`.

Scalar broadcasting for Particles, Directions, Spins and Polarization

---

src/QEDbase.jl
src/particles/particle_spin_pol.jl
test/particles.jl

Added convenience function for the number of (definite) spins or pols represented by the respective type. For instance, `SpinUp()` represents one spin instance, whereas `AllSpin()` represents two.

Number of spins or pols

---

src/dirac_tensors.jl

Just a tiny for multiplication of BiSpinor * AdjointBiSpinor on GPU. The general dot product doesn't work on the GPU.

BiSpinor multiplication fix for GPU

---

Project.toml
src/QEDbase.jl

During the registration, auto-merge is blocked due to compatibility problems with `ConstructionBase`. See https://github.com/JuliaRegistries/General/pull/109685 for details. 
This hotfix removes `ConstructionBase` from the dependencies. It shall go directly to main, and will be backported to dev afterwards.

removed ConstructionBase from dependency

---

.gitlab-ci.yml
CHANGELOG.md
Project.toml
src/QEDbase.jl
test/core_compat/README.md
test/core_compat/four_momentum.jl
test/core_compat/lorentz_vector.jl
test/runtests.jl

Add `ConstructionBase` with the correct `[compat]` entry, and test for compatibility with `QEDcore`. 
This is a hotfix, because the current release is broken. Therefore, this goes directly into `main` and is immediately released as version 0.2.1.  
This change is rebased and merged to `dev` afterward.

Hotfix construction base

---

Project.toml
src/QEDbase.jl
src/cross_section/diff_cross_section.jl
src/cross_section/diff_probability.jl
src/cross_section/total_cross_section.jl
src/cross_section/total_probability.jl
test/cross_sections.jl
test/runtests.jl
test/test_implementation/TestImplementation.jl
test/test_implementation/groundtruths.jl
test/test_implementation/random_momenta.jl
test/test_implementation/test_model.jl
test/test_implementation/test_process.jl
test/test_implementation/utils.jl

This adds generic implementations for total and differential cross-sections and probabilities based only on the interfaces. 
Most of the functionality is copied from `QEDprocesses`, but adjusted to use `AbstractPhaseSpacePoint` and such.

Add cross section and probability

---

.github/workflows/BuildDeployDoc.yml
.github/workflows/formatter.yaml
.gitlab-ci.yml

Use 1.10 by default for docs building and formatting, extend used versions by 1.10 and release candidate for unit tests.

Update CI Julia version

---

src/QEDbase.jl
src/particles/direction.jl
test/particle_properties.jl

Add UnknownDirection

---

src/QEDbase.jl
src/interfaces/process.jl

Add functions:
```Julia
number_particles(proc_def::AbstractProcessDefinition, dir::ParticleDirection, species::AbstractParticleType)
number_particles(proc_def::AbstractProcessDefinition, particle::AbstractParticleStateful)
number_particles(proc_def::AbstractProcessDefinition, particle_type::Type{AbstractParticleStateful})
```
Closes #89

Add number_particles overloads

---

src/interfaces/process.jl
test/test_implementation/test_process.jl

Fix the interface for momentum generation

---

src/interfaces/phase_space_point.jl

Adds functions 
```Julia
momentum(psp::AbstractPhaseSpacePoint, dir::ParticleDirection, species::AbstractParticleType, n::Val{N})
momentum(psp::AbstractPhaseSpacePoint, dir::ParticleDirection, species::AbstractParticleType, n::Int)
```
to get the momentum of the n-th particle of the given species and direction from the `AbstractPhaseSpacePoint`. I provided two overloads: One with a compile-time constant N via `Val{N}` and one with a normal `n::Int`. The first one adds no overhead and is compiled away completely, but only if the given value is actually a compile-time constant, such as a literal `1`. 
The second overload is implemented separately and is faster than the first when `n` is not a compile-time constant. It still takes ~40ns on my machine, versus ~1ns when the first overload is …

Add momentum() function for psp

---

src/QEDbase.jl
src/interfaces/process.jl
test/interfaces/process.jl

Adds the functions `incoming_spin_pol`, `outgoing_spin_pol`, and `spin_pol` to the `AbstractProcessDefinition` interface. These can be implemented by specific processes, or rely on the provided default implementation which returns `AllSpin` or `AllPol` for each particle.
Closes #105

Spin and Polarization Interface for AbstractProcessDefinition

---

src/interfaces/phase_space_point.jl

Rewrite momenta function without broadcast, because GPUs do not like broadcasts in their kernels.
This is essentially ported from https://github.com/QEDjl-project/QEDprocesses.jl/pull/69 since this implementation moved here since that PR was opened.

Fix GPU incompatability of `momenta` implementation

---

src/QEDbase.jl
src/interfaces/lorentz_vectors/dirac_interaction.jl

Remove mul from exported functions and rename to _mul

---

.github/workflows/BuildDeployDoc.yml
docs/make.jl

Copy of: https://github.com/QEDjl-project/QEDprocesses.jl/pull/95

CI: set QED dependencies for doc build to dev branch version, if target branch is not main

---

Project.toml
docs/make.jl
src/QEDbase.jl
src/interfaces/coordinate_transformation.jl
test/interfaces/coordinate_transforms.jl
test/runtests.jl
test/test_implementation/TestImplementation.jl
test/test_implementation/groundtruths.jl
test/test_implementation/test_coord_trafo.jl

Following the suggestion made here: https://github.com/QEDjl-project/QEDcore.jl/pull/45#discussion_r1759565312

added coord trafo interface

---

.github/workflows/BuildDeployDoc.yml
.gitlab-ci.yml

Use overworked CI script to setup dev branch Julia environment. The CI scripts allows to resolve circular dependencies and modify compat entries of dependencies, if own project version was updated.

CI: modify compat entries in docs build and integration tests

---

Project.toml
docs/make.jl
docs/src/library/phase_space_layout.md
src/QEDbase.jl
src/implementations/phase_space_layout/build_momenta.jl
src/interfaces/phase_space_layout.jl
test/interfaces/phase_space_layout.jl
test/runtests.jl
test/test_implementation/TestImplementation.jl
test/test_implementation/groundtruths.jl
test/test_implementation/test_phase_space_layout.jl

Adds the phase space layout (PSL) interface
Edit: 
The remaining todos are moved to #140

Phase space layout interface

---

src/QEDbase.jl
src/implementations/particle/print.jl
src/mocks/model/test_impl.jl
src/mocks/phase_space_layout/test_impl.jl
src/mocks/process/test_impl.jl
src/utils.jl
test/interfaces/particles.jl

adds: 
* generic `Base.show` for `AbstractParticleTypes`
* `Base.show` for some mocks
This should be merged **before**: #150 and https://github.com/QEDjl-project/QEDcore.jl/pull/94

[patch] add some shows
